# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml

cxx_compiler_version:   # [linux]
  - '14'                # [linux]
  - '14'                # [linux]

c_stdlib_version:       # [linux]
  - '2.17'              # [linux]
  - '2.17'              # [linux]

cuda_compiler_version:  # [linux]
  - '12.6'              # [linux]
  - '12.9'              # [linux]
