# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml

c_stdlib_version:  # [linux]
  - '2.17'         # [linux]
  - '2.17'         # [linux]

cuda_compiler_version:  # [linux]
  - '12.6'              # [linux]
  - '12.9'              # [linux]

cuda_compiler_version_min:  # [linux]
  - '12.6'                  # [linux]
  - '12.9'                  # [linux]

c_compiler_version:  # [linux]
  - '13'             # [linux]
  - '14'             # [linux]

cxx_compiler_version:  # [linux]
  - '13'               # [linux]
  - '14'               # [linux]

fortran_compiler_version:  # [linux]
  - '13'                   # [linux]
  - '14'                   # [linux]
