# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml

c_stdlib_version:
  - '2.17'
  - '2.17'

cuda_compiler_version:
  - '12.6'
  - '12.9'

cuda_compiler_version_min:
  - '12.6'
  - '12.9'

c_compiler_version:
  - '13'
  - '14'

cxx_compiler_version:
  - '13'
  - '14'

fortran_compiler_version:
  - '13'
  - '14'
