# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml

cxx_compiler_version:
  - '14'
  - '14'

c_stdlib_version:
  - '2.17'
  - '2.17'

cuda_compiler_version:
  - '12.6'
  - '12.9'
