{% set name = "causal-conv1d" %}
{% set version = "1.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/Dao-AILab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 198b4ebd9d4068e11b8742aaadfcb6304786cc752ce0fc46bf325c853ca49bc0

build:
  number: 2
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  script:
    - export CAUSAL_CONV1D_FORCE_BUILD=TRUE      # [unix]
    - export CAUSAL_CONV1D_FORCE_CXX11_ABI=TRUE  # [unix]
    - set CAUSAL_CONV1D_FORCE_BUILD=TRUE      # [win]
    - set CAUSAL_CONV1D_FORCE_CXX11_ABI=TRUE  # [win]
    - sed -i.bak 's@"ninja"@#"ninja"@g' setup.py
    - {{ PYTHON }} -m build --wheel --no-isolation --skip-dependency-check .
    - {{ PYTHON }} -m pip install dist/causal_conv1d-*.whl --no-deps -vv
  ignore_prefix_files:
    - x86_64-conda-linux-gnu/lib/libgfortran.so*
    - lib/gcc/x86_64-conda-linux-gnu/*/libhwasan.so
  ignore_run_exports:
    - python
    - packaging
  skip: true  # [cuda_compiler_version == "None" or cuda_compiler_version == "11.8" or win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - {{ stdlib('c') }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - cython                                # [build_platform != target_platform]
    - sed     # [unix]
    - m2-sed  # [win]
    - python                                # [build_platform != target_platform]
    - pytorch                               # [build_platform != target_platform]
  host:
    - cuda-toolkit
    - ninja
    - packaging
    - pip
    - python
    - python-build
    - pytorch
    - setuptools >=18.0
    - wheel
  run:
    - cuda-cudart
    - packaging
    - python
    - pytorch

test:
  imports:
    - causal_conv1d
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Dao-AILab/causal-conv1d
  summary: Causal depthwise conv1d in CUDA, with a PyTorch interface
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
