{% set name = "causal-conv1d" %}
{% set version = "1.5.0.post8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/Dao-AILab/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 100fcc9f7db5888dc01d3fc53d0ea6f168b91128994d41a82ecec07c8eb7d9db

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [cuda_compiler_version == "None"]
  skip: true  # [cuda_compiler_version == "11.8"]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - cython
    - ninja
    - pip
    - python
    - pytorch
    - setuptools >=18.0
  run:
    - cuda-cudart
    - packaging
    - python
    - pytorch

test:
  imports:
    - causal_conv1d
  # removed pip check because ninja is not available
  # see https://github.com/conda-forge/ninja-feedstock/issues/26
  # TODO: Enable pip check with a release with https://github.com/Dao-AILab/causal-conv1d/pull/50

about:
  home: https://github.com/Dao-AILab/causal-conv1d
  summary: Causal depthwise conv1d in CUDA, with a PyTorch interface
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
